services:
  streamer-bot:
    image: streamerbot
    restart: unless-stopped
    container_name: streamer-bot
    build:
      context: .
      dockerfile: StreamerBot/Dockerfile
    environment:
      DISCORD__TOKEN: "${DISCORD_TOKEN}"